[platformio]
src_dir = ATS_EX

[env:nanoatmega328]
; Old bootloader (57600 baud). Use nanoatmega328new for the new bootloader (115200).
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
lib_deps =
    pu2clr/PU2CLR SI4735
    datacute/Tiny4kOLED
    datacute/TinyOLED-Fonts

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
lib_deps =
    pu2clr/PU2CLR SI4735
    datacute/Tiny4kOLED
    datacute/TinyOLED-Fonts
